#!/usr/bin/env python3

import sys
from math import *
import __calculations__ as calc

def get_args():
    args = []
    if (len(sys.argv) < 3 or len(sys.argv) > 5):
        sys.exit(84)
    try:
        for i in range(1, len(sys.argv)):
            args.append(int(sys.argv[i]))
    except ValueError:
        sys.exit(84)
    if (args[0] < 0 or args[0] > 200):
        sys.exit(84)
    if (len(sys.argv) >= 4):
        if (args[2] < 0 or args[2] > 200):
            sys.exit(84)
    if (len(sys.argv) >= 5):
        if (args[3] < 0 or args[3] > 200):
            sys.exit(84)
    return args

def main():
    args = get_args()
    if (len(sys.argv) == 3):
        calc.calc_no_iq_args(args)
    if (len(sys.argv) == 4):
        calc.calc_1_iq_args(args)
    if (len(sys.argv) == 5):
        calc.calc_2_iq_args(args)

main()